kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: otel-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP
  - containerPort: 30317
    hostPort: 4317
    protocol: TCP
  - containerPort: 30318
    hostPort: 4318
    protocol: TCP