grafana:
  adminPassword: 'admin'
  service:
    type: NodePort
    port: 80
    nodePort: 30000

prometheus:
  prometheusSpec:
    resources: 
      requests:
        memory: "400Mi" 
      limits: 
        memory: "600Mi"
    retention: "5d"
    storageSpec: 
      volumeClaimTemplate: 
        spec: 
          resources: 
            requests: 
              storage: "2Gi"
alertmanager:
  alertmanagerSpec:
    resources: 
      requests:
        memory: "100Mi"
      limits: 
        memory: "200Mi"
    storage: 
      volumeClaimTemplate: 
        spec: 
          resources: 
            requests:
              storage: "1Gi" 